from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker
import openai
from langchain_openai.embeddings import OpenAIEmbeddings
from langchain_postgres import PGVector

# Database and API configurations
DATABASE_URL = "postgresql://postgres:213021181@localhost/_langchain1"
openai_api_key = ""

# Initialize SQLAlchemy engine and session
engine = create_engine(DATABASE_URL)
Session = sessionmaker(bind=engine)
session = Session()

# Initialize OpenAI Embeddings and PGVector
embeddings = OpenAIEmbeddings(api_key=openai_api_key, request_timeout=30)
vectorstore = PGVector(
    connection=engine,
    embeddings=embeddings,
    collection_name="bail_cases",
    embedding_length=1536,
    use_jsonb=True
)

# Initialize OpenAI client
openai.api_key = openai_api_key
client = openai
def query_section(ipc_section):
    """
    Queries the bail_cases database for IPC Section and enriches with OpenAI.

    Args:
        ipc_section (str): The IPC section or query input.

    Returns:
        str: Formatted response.
    """
    try:
        # Database Query
        result = session.execute(
            text("""
                SELECT section, bns_section, offense_type, bailable, bail_eligibility
                FROM bail_cases
                WHERE section = :section OR offense_type LIKE :query
                LIMIT 1
            """),
            {"section": ipc_section, "query": f"%{ipc_section}%"}
        ).fetchone()

        if result:
            section = result.section
            bns_section = result.bns_section or "Not Applicable"
            offense_type = result.offense_type
            bail_status = "Yes" if result.bailable else "No"
            bail_eligibility = result.bail_eligibility

            # Generate punishment, description, and process using OpenAI (ignoring BNS Section)
            prompt = f"""
Provide detailed legal information for:

Section: {section}
Offense Type: {offense_type}
Bail Status: {bail_status} (Eligibility: {bail_eligibility})

Format:
- Punishment:
- Description:
- Process to Follow:
"""
            openai_response = client.chat.completions.create(
                model="gpt-4",
                messages=[
                    {"role": "system", "content": "You are a legal expert."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=500
            )
            additional_info = openai_response.choices[0].message.content

            # Combine database results with AI output
            result_text = f"""
**Result:**
- IPC Section: {section}
- BNS Section: {bns_section}
- Offense Type: {offense_type}
- Bail Status: {bail_status} (Eligibility: {bail_eligibility})

{additional_info.strip()}
"""
            return result_text.strip()

        else:
            # No Database Result - Generate details from ChatGPT
            prompt = f"""
Provide detailed legal information for:

Query: {ipc_section}

Format:
- IPC Section:
- Offense Type:
- Bail Status:
- Punishment:
- Description:
- Process to Follow:
"""
            openai_response = client.chat.completions.create(
                model="gpt-4",
                messages=[
                    {"role": "system", "content": "You are a legal expert."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=500
            )
            content = openai_response.choices[0].message.content
            return f"No database results found. Here is the information generated by ChatGPT:\n\n{content.strip()}"

    except Exception as e:
        return f"An error occurred during query: {e}"

if __name__ == "__main__":
    print("Ready to accept user queries.")
    while True:
        user_query = input("Enter your query (type 'exit' to quit): ").strip()
        if user_query.lower() == "exit":
            print("Exiting query loop.")
            break
        response = query_section(user_query)
        print(f"\nResponse:\n{response}\n")